### ISSUE TITLE
Openlayers-plugin v 2.0.0 won't load in QGIS 3.4.1 installed via flatpak

### ISSUE THREAD

**Issue by MapperJeff** [sourcepole/qgis-openlayers-plugin#63] opened 2018-11-10 07:01 UTC
Pardon me if this is too similar to other posted issues.  Since this install was made via flatpak, I wasn't sure whether manually installing additional applications or libraries would be accessible to QGIS.
Thanks for any help.

I am running QGIS 3.4.1 installed via flatpak on the following machine:
- Operating System: KDE neon 5.14
- KDE Plasma Version: 5.14.3
- Qt Version: 5.11.2
- KDE Frameworks Version: 5.51.0
- Kernel Version: 4.15.0-38-generic
- OS Type: 64-bit
- Processors: 8 × Intel® Core™ i7-6700K CPU @ 4.00GHz
- Memory: 31.3 GiB of RAM

**Following is the full error message:**
Couldn't load plugin 'openlayers_plugin' due to an error when calling its classFactory() method 

ImportError: cannot import name 'QtWebKitWidgets' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/jeff/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/openlayers_plugin/__init__.py", line 26, in classFactory
    from .openlayers_plugin import OpenlayersPlugin
  File "/app/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jeff/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/openlayers_plugin/openlayers_plugin.py", line 33, in 
    from .openlayers_overview import OLOverview
  File "/app/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jeff/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/openlayers_plugin/openlayers_overview.py", line 23, in 
    from .openlayers_ovwidget import OpenLayersOverviewWidget
  File "/app/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jeff/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/openlayers_plugin/openlayers_ovwidget.py", line 34, in 
    from .ui_openlayers_ovwidget import Ui_Form
  File "/app/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jeff/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/openlayers_plugin/ui_openlayers_ovwidget.py", line 75, in 
    from PyQt5 import QtWebKitWidgets
ImportError: cannot import name 'QtWebKitWidgets'

Python version: 3.5.2 (default, Oct 11 2018, 08:33:18) [GCC 6.4.0] 
QGIS version: 3.4.1-Madeira Madeira, 383851c 

Python Path:
/app/share/qgis/python
/home/jeff/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/jeff/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/app/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-x86_64.egg
/app/lib/python3.5/site-packages/MarkupSafe-1.0-py3.5-linux-x86_64.egg
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-linux
/usr/lib/python3.5/lib-dynload
/usr/lib/python3.5/site-packages
/usr/lib/python3.5/site-packages/setuptools-22.0.5-py3.5.egg
/app/lib/python3.5/site-packages
/home/jeff/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python

**Comment by mone27** [comment] 2018-11-10 07:42
Notice: I am not the author nor the maintainer of this repo.

QtWebKit has been deprecated since Qt5.7 and replaced with QtWeb which is
based on chromium.
I haven't found anything whether QtWebKit is shipped with qgis (somewhere).
I believe that this is not a flatpak specific issue as I had the same
problem without flatpak.

**Comment by annanurov** [comment] 2020-02-29 14:23
Hello. A newbie here. What is flatpak? I'm trying to install openlayers (win10) via plugin manager. The plugin manager in qGIS does not have it in the list, so I downloaded the zip from here. qGIS still has some problem installing from zip.

**Comment by HusseinKabbout** [comment] 2020-03-11 16:20
@annanurov Look at #66

**Comment by HusseinKabbout** [comment] 2020-03-11 17:53
I will be closing this issue, because it's a duplicate of #56.

**Closed as completed by HusseinKabbout** 2020-03-11 17:53 UTC
